version: "3"

services:
    join-us-backend:
        build: 
          context: .
          dockerfile: server.dockerfile
        ports: 
           - "3000:3000"
        command: npm start
        depends_on:
          - database
        networks:
          - production

    database:
        image: mongo
        volumes:
          - data:/lucasgois/database
        networks:
          - production
        ports:
          - "27017:27017"


volumes:
    data:

networks:
    production:
        driver: bridge
